### ISSUE TITLE
Signing JWT with nodejs

### ISSUE THREAD

**Issue by reisenbauer** [nats-io/nkeys.js#24]
Hello,
i've got troubles creating a valid JWT + User seed for a nats Connection, my code:

```
let account = fromSeed(Buffer.from("SAADR32UHLDR5JTOGKHKFWERD5WD7QEGQK3YYJTUDLHS54QMXXXXXXXXXX"));
let accId = "ACJMTRQ6Y5BOI3IZ7AUDVRZNBWB6HLVCP7457TNGIMBTEKXXXXXXXXXX";
let user = createUser();
const header = base64url.encode(JSON.stringify({
    typ: "JWT",
    alg: "ed25519-key"
}))
const claims = {
    iss: account.getPublicKey().toString(),
    "name": "user_b",
    sub: user.getPublicKey().toString(),
    version: 2,
    "nats": {
        "pub": {},
        "sub": {},
        "subs": -1,
        "data": -1,
        "payload": -1,
        "bearer_token": true,
        "issuer_account": accId,
        "type": "user",
    }
};

const headers = base64url.encode(JSON.stringify(header))
const body = base64url.encode(JSON.stringify(claims));

const sigBase64Url = base64url.encode(account.sign(Buffer.from(headers + body)));
const jwt = `${headers}.${body}.${sigBase64Url}`;

console.log(jwt);
console.log(user.getSeed().toString())
```

About the keys:
```
# nsc list keys --show-seeds
+----------------------------------------------------------------------------------------+
|                                       Seeds Keys                                       |
+-------------+------------------------------------------------------------+-------------+
| Entity      | Private Key                                                | Signing Key |
+-------------+------------------------------------------------------------+-------------+
| myop        | SOAJ6RF4DRLVSVXUM3T7NCC3VVTGIAGUATIBDQYC7YFB6AO2XXXXXXXXXX |             |
| myop        | SOAEQD3QDL2LRB4IEVUGSJ63GNKRFQVNI3233TN22CFVDSHDXXXXXXXXXX | *           |
|  TEAM_A     | SAADR32UHLDR5JTOGKHKFWERD5WD7QEGQK3YYJTUDLHS54QMXXXXXXXXXX |             |
|  TEAM_A     | SAAG2BVIU5EBOXKTB3FQH5H7TTDA5RR64I3O64ARZKXYX6W4XXXXXXXXXX | *           |
```
```
# nsc list keys
+-----------------------------------------------------------------------------------------------+
|                                             Keys                                              |
+-------------+----------------------------------------------------------+-------------+--------+
| Entity      | Key                                                      | Signing Key | Stored |
+-------------+----------------------------------------------------------+-------------+--------+
| myop        | OCPNTPHLDSW7PBJYBAG53LS5ZBT47DJXY77AQD3ACZDEAFXXXXXXXXXX |             | *      |
| myop        | OBM5ZT4URLAQT56FQRWJXCZI6WFNRIE72U25ASOX5RUJWDXXXXXXXXXX | *           | *      |
|  TEAM_A     | ACJMTRQ6Y5BOI3IZ7AUDVRZNBWB6HLVCP7457TNGIMBTEKXXXXXXXXXX |             | *      |
|  TEAM_A     | AB44OKU6OCIYT5ASZHNOLB66AMDMMHBMGYEVFJGPC7QZ5WXXXXXXXXXX | *           | *      |
```

My Environment:

> Node Version: v19.7.0
> nkeys.js Version: 1.0.5

**The Error which i'm getting on the client:**
> Uncaught NatsError: 'Authorization Violation'

The client is working, when i'm using an JWT + Seed from a nsc created .creds file!

Anyone got an idea where i'm taking the wrong direction?

Thanks,
Stefan

**Comment by aricart** [comment]
Might be easier to simply use the jwt library...

https://github.com/nats-io/jwt.js

By simple inspection it looks correct.  Since you didn't show the creds
file not sure about that format.  Also if using bearer, should just use a
jet authenticator if using the javascript client

**Comment by aricart** [comment]
Here's an example with signing keys

https://github.com/nats-io/jwt.js/blob/main/tests/jwt_test.ts#L462

**Comment by reisenbauer** [comment]
Thanks for your feedback, with the references you've provided i managed to build up this:

```
import {
    encodeUser,
  } from "../src/jwt.ts";
import { 
    createAccount,
    fromSeed,
    createUser,}
    from "../src/nkeys.ts"

async function foo() {
    const akp = createAccount();
    const issuer = createAccount();
    const user = createUser();

    const xx = await encodeUser("U", user, akp, {}, { signer: issuer });

    console.log(xx);
    console.log(user.getPublicKey());
}

foo();
```

the created keys are then refused from the nats server with this error:
```
nats.js:6933 Uncaught NKeysError: nkeys: invalid seed
    at Bt.decodeSeed (nats.js:6933:19)
    at Object.fromSeed (nats.js:7112:11)
    at nats.js:7178:28
    at Object.authenticator (nats.js:7193:33)
    at new ct (nats.js:3932:58)
    at ht.processInfo (nats.js:4289:27)
    at ht.push (nats.js:4338:22)
    at et.parse (nats.js:3584:49)
    at nats.js:4082:37
```


the client itself:

```
import { connect,credsAuthenticator,StringCodec,jwtAuthenticator } from 'https://cdn.jsdelivr.net/npm/nats.ws@1.14.0/+esm'
const sc = StringCodec();
let oldval = false;

const conn = await connect({
    servers: [
        "wss://my-nats-server",
    ],
    authenticator:jwtAuthenticator(
        "eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJhdWQiOiJOQVRTIiwibmFtZSI6IlUiLCJzdWIiOiJVQUxZUDNSWVVLRFVESlQyRElDRUNJTVRHV0o1TUpZRTNETkNKRUJDMjNNM0ZETVhJSEZYUEpXVSIsIm5hdHMiOnsiZGF0YSI6LTEsInBheWxvYWQiOi0xLCJzdWJzIjotMSwiaXNzdWVyX2FjY291bnQiOiJBQjVaSlk1Qk1VS0dGTUtGUzVaNkNZMzM0R0FYSFlEWFJMNURPNFZIUTRBRE8zSUlVQzNaTlFISyIsInR5cGUiOiJ1c2VyIiwidmVyc2lvbiI6Mn0sImlzcyI6IkFCWFRWQk82Uk1ON1g3UEMzUEdGVUZOTURPWTNBRDJLTDM2RkdTQzZRMllZTENPSjZQVkROMzQzIiwiaWF0IjoxNjgxNDIxMzgxLCJqdGkiOiIxVmxSSUw1b0tqcWk4NmQ4Zk93ZWswdysrZThaNkNiTjdSYjhac3E2WlFPRDdpLzc3bnhZaCtLL1ViTkVMcmplbjZpQnpodTRpZExGeXppcWw3WTUyQT09In0.u9ik_invXAg7Nhv7Y2aAlhycJF-Jcb5VbZuTp-lepX-MZSP0oVjxHyoH_3aZGdV0oxYVIttAZbzQrvJ8Nq2dDg",
        new TextEncoder().encode("UALYP3RYUKDUDJT2DICECIMTGWJ5MJYE3DNCJEBC23M3FDMXIHFXPJWU")
    ),
});
```

**Comment by reisenbauer** [comment]
Got it up and running:
```

    async function foo() {
        const akp = fromSeed(Buffer.from("**PRIVATE KEY FROM ACCOUNT**"));
        const issuer = fromSeed(Buffer.from("**SIGNING KEY FROM ACCOUNT**"));
        const user = createUser();
        const jwt = await encodeUser("U", user, akp, {}, { signer: issuer });
        console.log("jwt", jwt)
        console.log("seed", Buffer.from(user.seed).toString())
    }
    foo();
```

thank you for your hints @aricart
